# pull official base image
FROM python:3.9-slim

# set work directory
WORKDIR /usr/src/todolist

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip


